### ISSUE TITLE
Worker node names and elastic IPs

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudman#100]
When adding a node, the worker VMs get a name such as `default-74bdbc`, which is not intuitive at all. A name based on the cluster name should be used.

Also, each worker gets an elastic IP, which doesn't seem like a necessary (or even desirable) element.

**Comment by nuwang** [comment]
Fixed in: https://github.com/CloudVE/cloudman-helm/commit/e3e629805407f40e557f87a37c40690e5644f5f1
https://github.com/CloudVE/cloudlaunch-helm/commit/d466b698f041b24b7e2d819e06d2db982849912f
https://github.com/CloudVE/cloudman-boot/commit/bd68e1b9c4eac9fadf3b8559359a286fcfd6f0c8

New issue for workers getting public ip: https://github.com/galaxyproject/cloudman/issues/103
