### ISSUE TITLE
Specify VPC? [Enhancement]

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/cloudman#28]
Hello again,
I'm working under a corporate AWS account with an individual IAM user. I can't specify a default VPC and I have to run Galaxy in a particular VPC. Could VPC selection be implemented in Cloudman and/or Cloudlaunch? I see in the Changelog that in August, support for VPC was added in some sense, but I'm not sure how to leverage this and/or specify it while using cloudlaunch. Will this be part of the larger October Galaxy release?

**Comment by afgane** [comment]
I believe the missing link would need be added to Cloudlaunch. Some tweaks might be necessary in CloudMan as well but given it handles the default VPC, I believe this should be OK. 

BTW, a pretty significant upgrade to Cloudlaunch is planned but it'll take several months. We're currently working on a lowest common denominator - a multi-cloud lib that uses native libraries (https://github.com/gvlproject/cloudbridge) so gradually it'll trickle up to Cloudlaunch. Just a heads up on all of this since it may impact this feature as well.

**Comment by MatthewRalston** [comment]
Does this mean that selection of the VPC could/should be a cloudlaunch specific feature? I can close this here.

**Comment by afgane** [comment]
Yes, I'd say moving it to Cloud Launch repo would be more appropriate. 

I'll close this issue here then and feel free to reopen it there.
