### ISSUE TITLE
 FAILURE Task failed: Parameter validation failed: Missing required parameter in input: "ImageId"

### ISSUE THREAD

**Issue by kpoterlowicz** [galaxyproject/cloudman#75]
Hi, When I do [Getting](url) Started with Galaxy on the Cloud I get the following FAILURE Task failed: Parameter validation failed: Missing required parameter in input: "ImageId" (see attached screenshot)

Kind regards,
Krzys
![screenshot from 2017-11-14 14 53 13](https://user-images.githubusercontent.com/18723544/32786560-335b15b2-c94c-11e7-8003-fa814f928c30.jpg)

**Comment by nuwang** [comment]
@kpoterlowicz Thanks for reporting this - this has been fixed in: https://github.com/CloudVE/djcloudbridge/commit/02e12ffc06d798c32ba0a8e178c422c947f97ed5 and https://github.com/CloudVE/djcloudbridge/commit/b4d4b23305d858d0e7ecea75c4670d5e0744460b
I'll close this for now but please reopen if you run into any issues again.
