### ISSUE TITLE
Not able to set admin users

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudman#95]
The config map (for `galaxy.yml` at least) does not get updated when edited via CloudMan's app config editor, and in turn the application configs are not changed. Direct config map changes (e.g., via Rancher) work and are reflected so this is a CloudMan issue.

**Comment by nuwang** [comment]
This was caused by the initial helm deployment status being in a 'FAILED' state for Galaxy - in turn caused by a stale archive that was failing a migrate job. Therefore, any invocation of `helm upgrade` would also fail. However, we should still detect this failure and mark the Galaxy instance as unavailable in the cloudman UI, so there's a different issue outstanding.
